# Generated by Django 4.0.3 on 2022-04-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
            ],
            options={
                'verbose_name_plural': 'Beceriler',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.CreateModel(
            name='RelCandidateAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ability', verbose_name='Beceri')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.candidateinfo', verbose_name='Aday')),
            ],
            options={
                'verbose_name_plural': 'Aday Beceri İlişkileri',
            },
        ),
    ]
