# Generated by Django 4.0.3 on 2022-04-03 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ability_alter_user_options_relcandidateability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='İlan Tarihi')),
                ('position_level', models.CharField(max_length=50, verbose_name='Pozisyon Seviyesi')),
                ('working_type', models.CharField(max_length=50, verbose_name='Çalışma Tipi')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('department', models.CharField(max_length=100, verbose_name='Departman')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company', verbose_name='Şirket')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'İlanlar',
            },
        ),
    ]
