# Generated by Django 4.0.3 on 2022-04-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelCandidateAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.advert', verbose_name='Aday')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.candidateinfo', verbose_name='Aday')),
            ],
            options={
                'verbose_name_plural': 'Aday İlan İlişkileri',
            },
        ),
    ]
