# Generated by Django 4.0.3 on 2022-04-06 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_relcandidateuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelUserSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='Bölüm')),
                ('start', models.DateField(verbose_name='Başlangıç')),
                ('end', models.DateField(verbose_name='Bitiş')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.school', verbose_name='Okul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.candidateinfo', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı Okul İlişkileri',
            },
        ),
        migrations.DeleteModel(
            name='RelCandidateSchool',
        ),
    ]
