# Generated by Django 4.0.3 on 2022-04-06 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reluserschool_delete_relcandidateschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reluserschool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
