# Generated by Django 4.0.3 on 2022-04-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.advert', verbose_name='İlan')),
            ],
            options={
                'verbose_name_plural': 'İlan Etiketleri',
            },
        ),
    ]
