# Generated by Django 4.0.3 on 2022-04-07 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_adverttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelUserAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.advert', verbose_name='Aday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Aday')),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı İlan İlişkileri',
            },
        ),
        migrations.DeleteModel(
            name='RelCandidateAdvert',
        ),
    ]
