from api.views.user import *
from api.views.ability import *
from api.views.company import *
from api.views.school import *
from api.views.advert import *
from api.views.candidate import *
from api.views.rel_user_advert import *
from api.views.rel_candidate_ability import *
from api.views.rel_user_school import *
from api.views.rel_company_user import *
from api.views.rel_candidate_user import *
from api.views.token import *
from api.views.user_experience import *
from api.views.advert_tag import *
