from api.serializers.user import *
from api.serializers.ability import *
from api.serializers.company import *
from api.serializers.school import *
from api.serializers.advert import *
from api.serializers.candidate import *
from api.serializers.rel_user_advert import *
from api.serializers.rel_candidate_ability import *
from api.serializers.rel_user_school import *
from api.serializers.rel_company_user import *
from api.serializers.rel_candidate_user import *
from api.serializers.user_experience import *
